---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: backendjwts.dp.wso2.com
spec:
  group: dp.wso2.com
  names:
    kind: BackendJWT
    listKind: BackendJWTList
    plural: backendjwts
    singular: backendjwt
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BackendJWT is the Schema for the backendjwts API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BackendJWTSpec defines the desired state of BackendJWT
            properties:
              customClaims:
                description: CustomClaims holds custom claims that needs to be added
                  to the jwt
                items:
                  description: CustomClaim holds custom claim information
                  properties:
                    claim:
                      description: Claim name
                      minLength: 1
                      type: string
                    type:
                      default: string
                      description: Claim type
                      enum:
                      - string
                      - int
                      - float
                      - bool
                      - long
                      - date
                      type: string
                    value:
                      description: Claim value
                      minLength: 1
                      type: string
                  required:
                  - type
                  type: object
                nullable: true
                type: array
              encoding:
                default: Base64
                description: Encoding of the JWT token
                enum:
                - Base64
                - Base64url
                type: string
              header:
                default: X-JWT-Assertion
                description: Header of the JWT token
                minLength: 1
                type: string
              signingAlgorithm:
                default: SHA256withRSA
                description: Signing algorithm of the JWT token
                type: string
              tokenTTL:
                default: 3600
                description: TokenTTL time to live for the backend JWT token in seconds
                format: int32
                type: integer
            type: object
          status:
            description: BackendJWTStatus defines the observed state of BackendJWT
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
