---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: aiproviders.dp.wso2.com
spec:
  group: dp.wso2.com
  names:
    kind: AIProvider
    listKind: AIProviderList
    plural: aiproviders
    singular: aiprovider
  scope: Namespaced
  versions:
  - name: v1alpha3
    schema:
      openAPIV3Schema:
        description: AIProvider is the Schema for the aiproviders API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AIProviderSpec defines the desired state of AIProvider
            properties:
              model:
                description: ValueDetails defines the value details
                properties:
                  in:
                    type: string
                  value:
                    type: string
                required:
                - in
                - value
                type: object
              organization:
                type: string
              providerAPIVersion:
                type: string
              providerName:
                minLength: 1
                type: string
              rateLimitFields:
                description: RateLimitFields defines the Rate Limit fields
                properties:
                  completionToken:
                    description: ValueDetails defines the value details
                    properties:
                      in:
                        type: string
                      value:
                        type: string
                    required:
                    - in
                    - value
                    type: object
                  promptTokens:
                    description: ValueDetails defines the value details
                    properties:
                      in:
                        type: string
                      value:
                        type: string
                    required:
                    - in
                    - value
                    type: object
                  totalToken:
                    description: ValueDetails defines the value details
                    properties:
                      in:
                        type: string
                      value:
                        type: string
                    required:
                    - in
                    - value
                    type: object
                required:
                - completionToken
                - promptTokens
                - totalToken
                type: object
            required:
            - model
            - organization
            - providerAPIVersion
            - providerName
            - rateLimitFields
            type: object
          status:
            description: AIProviderStatus defines the observed state of AIProvider
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha4
    schema:
      openAPIV3Schema:
        description: AIProvider is the Schema for the aiproviders API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AIProviderSpec defines the desired state of AIProvider
            properties:
              model:
                description: ValueDetails defines the value details
                properties:
                  in:
                    type: string
                  value:
                    type: string
                required:
                - in
                - value
                type: object
              organization:
                type: string
              providerAPIVersion:
                type: string
              providerName:
                minLength: 1
                type: string
              rateLimitFields:
                description: RateLimitFields defines the Rate Limit fields
                properties:
                  completionToken:
                    description: ValueDetails defines the value details
                    properties:
                      in:
                        type: string
                      value:
                        type: string
                    required:
                    - in
                    - value
                    type: object
                  promptTokens:
                    description: ValueDetails defines the value details
                    properties:
                      in:
                        type: string
                      value:
                        type: string
                    required:
                    - in
                    - value
                    type: object
                  totalToken:
                    description: ValueDetails defines the value details
                    properties:
                      in:
                        type: string
                      value:
                        type: string
                    required:
                    - in
                    - value
                    type: object
                required:
                - completionToken
                - promptTokens
                - totalToken
                type: object
              supportedModels:
                items:
                  type: string
                type: array
            required:
            - model
            - organization
            - providerAPIVersion
            - providerName
            - rateLimitFields
            type: object
          status:
            description: AIProviderStatus defines the observed state of AIProvider
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
