---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: tokenissuers.dp.wso2.com
spec:
  group: dp.wso2.com
  names:
    kind: TokenIssuer
    listKind: TokenIssuerList
    plural: tokenissuers
    singular: tokenissuer
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TokenIssuer is the Schema for the tokenIssuer API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: TokenIssuerSpec defines the desired state of TokenIssuer
            properties:
              claimMappings:
                description: ClaimMappings denotes the claim mappings of the jwt
                items:
                  description: ClaimMapping defines the reference configuration
                  properties:
                    localClaim:
                      description: LocalClaim denotes the local claim
                      type: string
                    remoteClaim:
                      description: RemoteClaim denotes the remote claim
                      type: string
                  required:
                  - localClaim
                  - remoteClaim
                  type: object
                type: array
              consumerKeyClaim:
                description: ConsumerKeyClaim denotes the claim key of the consumer
                  key.
                minLength: 1
                type: string
              issuer:
                description: Issuer denotes the issuer of the Token Issuer.
                minLength: 1
                type: string
              name:
                description: |-
                  Name is the unique name of the Token Issuer in
                  the Organization defined . "Organization/Name" can
                  be used to uniquely identify an Issuer.
                minLength: 1
                type: string
              organization:
                description: Organization denotes the organization of the Token Issuer.
                minLength: 1
                type: string
              scopesClaim:
                description: ScopesClaim denotes the claim key of the scopes.
                minLength: 1
                type: string
              signatureValidation:
                description: SignatureValidation denotes the signature validation
                  method of jwt
                properties:
                  certificate:
                    description: Certificate denotes the certificate information
                    properties:
                      certificateInline:
                        description: CertificateInline is the Inline Certificate entry
                        type: string
                      configMapRef:
                        description: ConfigMapRef denotes the reference to the ConfigMap
                          that contains the Certificate
                        properties:
                          key:
                            description: Key of the secret or configmap
                            minLength: 1
                            type: string
                          name:
                            description: Name of the secret or configmap
                            minLength: 1
                            type: string
                        required:
                        - key
                        - name
                        type: object
                      secretRef:
                        description: SecretRef denotes the reference to the Secret
                          that contains the Certificate
                        properties:
                          key:
                            description: Key of the secret or configmap
                            minLength: 1
                            type: string
                          name:
                            description: Name of the secret or configmap
                            minLength: 1
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                  jwks:
                    description: JWKS denotes the JWKS endpoint information
                    properties:
                      tls:
                        description: TLS denotes the TLS configuration of the JWKS
                          endpoint
                        properties:
                          certificateInline:
                            description: CertificateInline is the Inline Certificate
                              entry
                            type: string
                          configMapRef:
                            description: ConfigMapRef denotes the reference to the
                              ConfigMap that contains the Certificate
                            properties:
                              key:
                                description: Key of the secret or configmap
                                minLength: 1
                                type: string
                              name:
                                description: Name of the secret or configmap
                                minLength: 1
                                type: string
                            required:
                            - key
                            - name
                            type: object
                          secretRef:
                            description: SecretRef denotes the reference to the Secret
                              that contains the Certificate
                            properties:
                              key:
                                description: Key of the secret or configmap
                                minLength: 1
                                type: string
                              name:
                                description: Name of the secret or configmap
                                minLength: 1
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      url:
                        description: URL is the URL of the JWKS endpoint
                        type: string
                    required:
                    - url
                    type: object
                type: object
              targetRef:
                description: TargetRef denotes the reference to the which gateway
                  it applies to
                properties:
                  group:
                    description: Group is the group of the target resource.
                    maxLength: 253
                    pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                    type: string
                  kind:
                    description: Kind is kind of the target resource.
                    maxLength: 63
                    minLength: 1
                    pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                    type: string
                  name:
                    description: Name is the name of the target resource.
                    maxLength: 253
                    minLength: 1
                    type: string
                  namespace:
                    description: |-
                      Namespace is the namespace of the referent. When unspecified, the local
                      namespace is inferred. Even when policy targets a resource in a different
                      namespace, it MUST only apply to traffic originating from the same
                      namespace as the policy.
                    maxLength: 63
                    minLength: 1
                    pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                    type: string
                required:
                - group
                - kind
                - name
                type: object
            required:
            - consumerKeyClaim
            - issuer
            - name
            - organization
            - scopesClaim
            - signatureValidation
            type: object
          status:
            description: TokenIssuerStatus defines the observed state of TokenIssuer
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: TokenIssuer is the Schema for the tokenissuers API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: TokenIssuerSpec defines the desired state of TokenIssuer
            properties:
              claimMappings:
                description: ClaimMappings denotes the claim mappings of the jwt
                items:
                  description: ClaimMapping defines the reference configuration
                  properties:
                    localClaim:
                      description: LocalClaim denotes the local claim
                      type: string
                    remoteClaim:
                      description: RemoteClaim denotes the remote claim
                      type: string
                  required:
                  - localClaim
                  - remoteClaim
                  type: object
                type: array
              consumerKeyClaim:
                description: ConsumerKeyClaim denotes the claim key of the consumer
                  key.
                minLength: 1
                type: string
              environments:
                description: Environments denotes the environments that are applicable
                  for the token issuer.
                items:
                  type: string
                nullable: true
                type: array
              issuer:
                description: Issuer denotes the issuer of the Token Issuer.
                minLength: 1
                type: string
              name:
                description: |-
                  Name is the unique name of the Token Issuer in
                  the Organization defined . "Organization/Name" can
                  be used to uniquely identify an Issuer.
                minLength: 1
                type: string
              organization:
                description: Organization denotes the organization of the Token Issuer.
                minLength: 1
                type: string
              scopesClaim:
                description: ScopesClaim denotes the claim key of the scopes.
                minLength: 1
                type: string
              signatureValidation:
                description: SignatureValidation denotes the signature validation
                  method of jwt
                properties:
                  certificate:
                    description: Certificate denotes the certificate information
                    properties:
                      certificateInline:
                        description: CertificateInline is the Inline Certificate entry
                        type: string
                      configMapRef:
                        description: ConfigMapRef denotes the reference to the ConfigMap
                          that contains the Certificate
                        properties:
                          key:
                            description: Key of the secret or configmap
                            minLength: 1
                            type: string
                          name:
                            description: Name of the secret or configmap
                            minLength: 1
                            type: string
                        required:
                        - key
                        - name
                        type: object
                      secretRef:
                        description: SecretRef denotes the reference to the Secret
                          that contains the Certificate
                        properties:
                          key:
                            description: Key of the secret or configmap
                            minLength: 1
                            type: string
                          name:
                            description: Name of the secret or configmap
                            minLength: 1
                            type: string
                        required:
                        - key
                        - name
                        type: object
                    type: object
                  jwks:
                    description: JWKS denotes the JWKS endpoint information
                    properties:
                      tls:
                        description: TLS denotes the TLS configuration of the JWKS
                          endpoint
                        properties:
                          certificateInline:
                            description: CertificateInline is the Inline Certificate
                              entry
                            type: string
                          configMapRef:
                            description: ConfigMapRef denotes the reference to the
                              ConfigMap that contains the Certificate
                            properties:
                              key:
                                description: Key of the secret or configmap
                                minLength: 1
                                type: string
                              name:
                                description: Name of the secret or configmap
                                minLength: 1
                                type: string
                            required:
                            - key
                            - name
                            type: object
                          secretRef:
                            description: SecretRef denotes the reference to the Secret
                              that contains the Certificate
                            properties:
                              key:
                                description: Key of the secret or configmap
                                minLength: 1
                                type: string
                              name:
                                description: Name of the secret or configmap
                                minLength: 1
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        type: object
                      url:
                        description: URL is the URL of the JWKS endpoint
                        type: string
                    required:
                    - url
                    type: object
                type: object
              targetRef:
                description: TargetRef denotes the reference to the which gateway
                  it applies to
                properties:
                  group:
                    description: Group is the group of the target resource.
                    maxLength: 253
                    pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                    type: string
                  kind:
                    description: Kind is kind of the target resource.
                    maxLength: 63
                    minLength: 1
                    pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                    type: string
                  name:
                    description: Name is the name of the target resource.
                    maxLength: 253
                    minLength: 1
                    type: string
                  namespace:
                    description: |-
                      Namespace is the namespace of the referent. When unspecified, the local
                      namespace is inferred. Even when policy targets a resource in a different
                      namespace, it MUST only apply to traffic originating from the same
                      namespace as the policy.
                    maxLength: 63
                    minLength: 1
                    pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                    type: string
                required:
                - group
                - kind
                - name
                type: object
            required:
            - consumerKeyClaim
            - issuer
            - name
            - organization
            - scopesClaim
            - signatureValidation
            type: object
          status:
            description: TokenIssuerStatus defines the observed state of TokenIssuer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
