[package]
org = "wso2"
name = "devportal_service"
version = "0.0.1-m7"
distribution = "2201.2.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.5.0"

[[dependency]]
org = "wso2"
name = "apk_common_lib"
version = "0.0.1-SNAPSHOT"
repository = "local"

[[platform.java11.dependency]]
groupId = "org.wso2.apk"
artifactId = "org.wso2.apk.devportal"
version = "0.0.1-m7"
path = "../java/build/libs/org.wso2.apk.devportal-0.0.1-m7.jar"

# transitive dependency of org.wso2.apk:org.wso2.apk.devportal:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "commons-logging"
artifactId = "commons-logging"
version = "1.1.1"

# transitive dependency of org.wso2.apk:org.wso2.apk.devportal:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "commons-validator"
artifactId = "commons-validator"
version = "1.7"

# transitive dependency of commons-validator:commons-validator:1.7
[[platform.java11.dependency]]
groupId = "commons-beanutils"
artifactId = "commons-beanutils"
version = "1.9.4"

# transitive dependency of commons-validator:commons-validator:1.7
[[platform.java11.dependency]]
groupId = "commons-digester"
artifactId = "commons-digester"
version = "2.1"

# transitive dependency of commons-validator:commons-validator:1.7
[[platform.java11.dependency]]
groupId = "commons-collections"
artifactId = "commons-collections"
version = "3.2.2"

# transitive dependency of org.wso2.apk:org.wso2.apk.devportal:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "org.openapitools"
artifactId = "openapi-generator"
version = "6.2.1"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger.parser.v3"
artifactId = "swagger-parser"
version = "2.1.6"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger.parser.v3"
artifactId = "swagger-parser-v2-converter"
version = "2.1.6"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger"
artifactId = "swagger-core"
version = "1.6.8"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger"
artifactId = "swagger-models"
version = "1.6.8"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger"
artifactId = "swagger-annotations"
version = "1.6.8"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "javax.validation"
artifactId = "validation-api"
version = "1.1.0.Final"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger"
artifactId = "swagger-parser"
version = "1.0.63"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger"
artifactId = "swagger-compat-spec-parser"
version = "1.0.63"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.java-json-tools"
artifactId = "json-schema-validator"
version = "2.2.14"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.java-json-tools"
artifactId = "jackson-coreutils-equivalence"
version = "1.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.java-json-tools"
artifactId = "json-schema-core"
version = "1.2.14"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.java-json-tools"
artifactId = "uri-template"
version = "0.10"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.mozilla"
artifactId = "rhino"
version = "1.7.7.2"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.sun.mail"
artifactId = "mailapi"
version = "1.6.2"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.googlecode.libphonenumber"
artifactId = "libphonenumber"
version = "8.11.1"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "net.sf.jopt-simple"
artifactId = "jopt-simple"
version = "5.0.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.java-json-tools"
artifactId = "json-patch"
version = "1.13"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.java-json-tools"
artifactId = "msg-simple"
version = "1.2"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.java-json-tools"
artifactId = "btf"
version = "1.3"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.java-json-tools"
artifactId = "jackson-coreutils"
version = "2.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpclient"
version = "4.5.13"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpcore"
version = "4.4.13"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "commons-codec"
artifactId = "commons-codec"
version = "1.11"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger.core.v3"
artifactId = "swagger-models"
version = "2.2.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger.parser.v3"
artifactId = "swagger-parser-core"
version = "2.1.6"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger.parser.v3"
artifactId = "swagger-parser-v3"
version = "2.1.6"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger.core.v3"
artifactId = "swagger-core"
version = "2.2.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "jakarta.xml.bind"
artifactId = "jakarta.xml.bind-api"
version = "2.3.2"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "jakarta.activation"
artifactId = "jakarta.activation-api"
version = "1.2.1"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.datatype"
artifactId = "jackson-datatype-jsr310"
version = "2.13.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "io.swagger.core.v3"
artifactId = "swagger-annotations"
version = "2.2.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "jakarta.validation"
artifactId = "jakarta.validation-api"
version = "2.0.2"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.dataformat"
artifactId = "jackson-dataformat-yaml"
version = "2.13.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.yaml"
artifactId = "snakeyaml"
version = "1.33"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.samskivert"
artifactId = "jmustache"
version = "1.14"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.jknack"
artifactId = "handlebars"
version = "4.2.1"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.jknack"
artifactId = "handlebars-jackson2"
version = "4.2.1"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.11.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-ext"
version = "1.7.36"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-api"
version = "1.7.36"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-simple"
version = "1.7.36"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-lang3"
version = "3.12.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-text"
version = "1.10.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "commons-cli"
artifactId = "commons-cli"
version = "1.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.google.guava"
artifactId = "guava"
version = "30.1.1-jre"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.google.guava"
artifactId = "failureaccess"
version = "1.0.1"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.google.guava"
artifactId = "listenablefuture"
version = "9999.0-empty-to-avoid-conflict-with-guava"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.google.code.findbugs"
artifactId = "jsr305"
version = "3.0.2"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.checkerframework"
artifactId = "checker-qual"
version = "3.8.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.google.errorprone"
artifactId = "error_prone_annotations"
version = "2.5.1"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.google.j2objc"
artifactId = "j2objc-annotations"
version = "1.3"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.datatype"
artifactId = "jackson-datatype-guava"
version = "2.13.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.13.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.atlassian.commonmark"
artifactId = "commonmark"
version = "0.11.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.mifmif"
artifactId = "generex"
version = "1.0.2"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "dk.brics.automaton"
artifactId = "automaton"
version = "1.11-8"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.curious-odd-man"
artifactId = "rgxgen"
version = "1.3"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.13.4.2"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.13.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.datatype"
artifactId = "jackson-datatype-joda"
version = "2.13.4"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "joda-time"
artifactId = "joda-time"
version = "2.10.8"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.joschi.jackson"
artifactId = "jackson-datatype-threetenbp"
version = "2.10.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.threeten"
artifactId = "threetenbp"
version = "1.4.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "org.openapitools"
artifactId = "openapi-generator-core"
version = "6.2.1"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "net.java.dev.jna"
artifactId = "jna"
version = "5.5.0"

# transitive dependency of org.openapitools:openapi-generator:6.2.1
[[platform.java11.dependency]]
groupId = "com.github.ben-manes.caffeine"
artifactId = "caffeine"
version = "2.8.1"

# transitive dependency of org.wso2.apk:org.wso2.apk.devportal:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "commons-lang"
artifactId = "commons-lang"
version = "2.4"
