apiVersion: dp.wso2.com/v1alpha5
kind: Backend
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: backend-sample
spec:
  # TODO(user): Add fields here
