apiVersion: dp.wso2.com/v1beta1
kind: API
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: api-sample
spec:
  # TODO(user): Add fields here
