confidence = 0.8
errorCode = 0
ignoreGeneratedHeader = false
severity = "warning"
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
exclude = ["apis/dp/v1alpha1/webhook_suite_test.go", "apis/dp/v1alpha2/webhook_suite_test.go", "apis/dp/v1alpha3/webhook_suite_test.go"]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unreachable-code]
[rule.redefines-builtin-id]
