---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha3-api
  failurePolicy: Fail
  name: mapi.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - apis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha3-apipolicy
  failurePolicy: Fail
  name: mapipolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - apipolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha2-api
  failurePolicy: Fail
  name: mapi.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha2-apipolicy
  failurePolicy: Fail
  name: mapipolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apipolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha2-authentication
  failurePolicy: Fail
  name: mauthentication.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - authentications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha1-apipolicy
  failurePolicy: Fail
  name: mapipolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apipolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha1-backend
  failurePolicy: Fail
  name: mbackend.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backends
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha1-backendjwt
  failurePolicy: Fail
  name: mbackendjwt.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backendjwts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha1-interceptorservice
  failurePolicy: Fail
  name: minterceptorservice.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - interceptorservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha3-ratelimitpolicy
  failurePolicy: Fail
  name: mratelimitpolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - ratelimitpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha3-ratelimitpolicy
  failurePolicy: Fail
  name: mratelimitpolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - ratelimitpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dp-wso2-com-v1alpha1-ratelimitpolicy
  failurePolicy: Fail
  name: mratelimitpolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ratelimitpolicies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha3-api
  failurePolicy: Fail
  name: vapi.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - apis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha3-apipolicy
  failurePolicy: Fail
  name: vapipolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - apipolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha2-api
  failurePolicy: Fail
  name: vapi.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha2-apipolicy
  failurePolicy: Fail
  name: vapipolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apipolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha2-authentication
  failurePolicy: Fail
  name: vauthentication.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - authentications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha1-apipolicy
  failurePolicy: Fail
  name: vapipolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apipolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha1-backend
  failurePolicy: Fail
  name: vbackend.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backends
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha1-backendjwt
  failurePolicy: Fail
  name: vbackendjwt.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backendjwts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha1-interceptorservice
  failurePolicy: Fail
  name: vinterceptorservice.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - interceptorservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dp-wso2-com-v1alpha1-ratelimitpolicy
  failurePolicy: Fail
  name: vratelimitpolicy.kb.io
  rules:
  - apiGroups:
    - dp.wso2.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ratelimitpolicies
  sideEffects: None
