# Copyright (c) 2025 WSO2 LLC. (http://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
{{- if and .Values.wso2.kgw.dp.enabled .Values.wso2.kgw.dp.configdeployer.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ template "kubernetes-gateway-helm.resource.prefix" . }}-api-create-scope-policy
  namespace: {{ .Release.Namespace }}
  labels:
    managed-by: "kgw"
  # annotations:
  #   "helm.sh/hook": post-install,post-upgrade
spec:
  targetRef:
    kind: HTTPRoute
    group: gateway.networking.k8s.io
    name: {{ template "kubernetes-gateway-helm.resource.prefix" . }}-config-deploy-api-route
  jwt:
    providers:
    - name: {{ template "kubernetes-gateway-helm.resource.prefix" . }}-idp-jwt-issuer
      issuer: {{ .Values.wso2.kgw.idp.issuer }}
      remoteJWKS:
        uri: {{ .Values.wso2.kgw.idp.signing.jwksEndpoint }}
  authorization:
    rules:
    - name: "api-create-rule"
      action: Allow
      principal:
        jwt:
          provider: {{ template "kubernetes-gateway-helm.resource.prefix" . }}-idp-jwt-issuer
          scopes:
          - apk:api_create
{{- end -}}
