{{- if and .Values.wso2.apk.dp.enabled .Values.wso2.apk.dp.configdeployer.enabled }}
apiVersion: dp.wso2.com/v1alpha5
kind: APIPolicy
metadata:
  name: "{{ template "apk-helm.resource.prefix" . }}-config-api-api-policy"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  override:
    backendJwtPolicy:
        name: "{{ template "apk-helm.resource.prefix" . }}-config-api-backendjwt"
  targetRef:
    group: gateway.networking.k8s.io
    kind: API
    name:  {{ template "apk-helm.resource.prefix" . }}-wso2-apk-config-deployer-api
{{- end}}