[package]
org = "wso2"
name = "backoffice_internal_service"
version = "0.0.1-SNAPSHOT"
distribution = "2201.2.2"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.5.0"
