[package]
org = "wso2"
name = "apk_common_lib"
version = "0.0.1-SNAPSHOT"
distribution = "2201.8.5"

[[platform.java11.dependency]]
groupId = "org.wso2.apk"
artifactId = "org.wso2.apk.common"
version = "0.0.1-SNAPSHOT"
path = "../java/build/libs/org.wso2.apk.common-0.0.1-SNAPSHOT.jar"

# transitive dependency of org.wso2.apk:org.wso2.apk.common:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "commons-logging"
artifactId = "commons-logging"
version = "1.1.1"

# transitive dependency of org.wso2.apk:org.wso2.apk.common:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "com.google.code.gson"
artifactId = "gson"
version = "2.10"

# transitive dependency of org.wso2.apk:org.wso2.apk.common:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.dataformat"
artifactId = "jackson-dataformat-yaml"
version = "2.18.0"

# transitive dependency of com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.18.0
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.18.0"

# transitive dependency of com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.18.0
[[platform.java11.dependency]]
groupId = "org.yaml"
artifactId = "snakeyaml"
version = "2.2"

# transitive dependency of com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.18.0
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.18.0"

# transitive dependency of org.wso2.apk:org.wso2.apk.common:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.18.0"

# transitive dependency of org.wso2.apk:org.wso2.apk.common:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "org.json"
artifactId = "json"
version = "20231013"

# transitive dependency of org.wso2.apk:org.wso2.apk.common:0.0.1-SNAPSHOT
[[platform.java11.dependency]]
groupId = "commons-lang"
artifactId = "commons-lang"
version = "2.4"
