# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.wso2.apk.dp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-cc-adapter-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.apk.dp.cc.adapter.deployment.replicas }}
  strategy:
    type: {{ .Values.wso2.apk.dp.cc.adapter.deployment.strategy }}
  selector:
    matchLabels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.cc.adapter.appName ) | indent 6}}
  template:
    metadata:
      labels:
        networkPolicyId: {{ .Values.wso2.apk.dp.cc.adapter.deployment.npi }}
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.cc.adapter.appName ) | indent 8}}
    spec:
      serviceAccountName: {{ .Values.wso2.apk.auth.serviceAccountName }}
      containers:
        - name: cc-adapter
          image: {{ .Values.wso2.apk.dp.cc.adapter.deployment.image }}
          imagePullPolicy: {{ .Values.wso2.apk.dp.cc.adapter.deployment.imagePullPolicy }}
          ports:
            - containerPort: 18000
              protocol: "TCP"
            - containerPort: 8765
              protocol: "TCP"
{{ include "apk-helm.deployment.resources" .Values.wso2.apk.dp.cc.adapter.deployment.resources | indent 10 }}
{{ include "apk-helm.deployment.env" .Values.wso2.apk.dp.cc.adapter.deployment.env | indent 10 }}
          env:
            - name: OPERATOR_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: cc-adapter-keystore-secret-volume
              mountPath: /home/wso2/security/keystore
            - name: cc-adapter-truststore-secret-volume
              mountPath: /home/wso2/security/truststore
            - name: cc-adapter-truststore-consul-secret-volume
              mountPath: /home/wso2/security/truststore/consul
            - name: cc-log-conf-volume
              mountPath: /home/wso2/conf/
            - mountPath: /home/wso2/check_health.sh
              name: cc-adapter-grpc-probe-script-conf-volume
              subPath: "check_health.sh"
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cc-adapter-webhook-server-cert
              readOnly: true
          # readinessProbe:
          #   exec:
          #     command: [ "sh", "check_health.sh" ]
          #   initialDelaySeconds: 8
          #   periodSeconds: 5
      volumes: 
        - name: cc-adapter-keystore-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-cc-adapter-keystore-secret
        - name: cc-adapter-truststore-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-cc-adapter-truststore-secret
        - name: cc-adapter-truststore-consul-secret-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-cc-adapter-truststore-consul-secret
        - name: cc-log-conf-volume
          configMap: 
            name: {{ template "apk-helm.resource.prefix" . }}-cc-log-conf
        - name: cc-adapter-grpc-probe-script-conf-volume
          configMap: 
            name: {{ template "apk-helm.resource.prefix" . }}-cc-adapter-grpc-probe-script-conf
            defaultMode: 0777
        - name: cc-adapter-webhook-server-cert
          secret:
            secretName: {{ template "apk-helm.resource.prefix" . }}-webhook-server-cert
            defaultMode: 420
{{- end -}}
