[package]
org = "wso2"
name = "idp_domain_service"
version = "0.0.1-m6"
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"

[build-options]
observabilityIncluded = true
