[package]
org = "wso2"
name = "idp_domain_service"
version = "1.3.0-beta"
distribution = "2201.10.2"

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"

[[platform.java11.dependency]]
groupId = "io.prometheus.jmx"
artifactId = "jmx_prometheus_javaagent"
version = "0.20.0"

[build-options]
observabilityIncluded = true
