[package]
org = "wso2"
name = "idp_domain_service"
version = "1.1.0-alpha"
distribution = "2201.8.0"

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"

[build-options]
observabilityIncluded = true
