[package]
org = "wso2"
name = "apk_keymanager_libs"
version = "0.0.1-SNAPSHOT"
distribution = "2201.10.2"

[[dependency]]
org = "wso2"
name = "apk_common_lib"
version = "0.0.1-SNAPSHOT"
repository = "local"