[package]
org = "wso2"
name = "admin_service"
version = "0.0.1-m10"
distribution = "2201.5.0"

[[dependency]]
org = "wso2"
name = "apk_common_lib"
version = "0.0.1-SNAPSHOT"
repository = "local"

[[dependency]]
org = "wso2"
name = "apk_keymanager_libs"
version="0.0.1-SNAPSHOT"
repository = "local"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"
