# permissions for end users to edit interceptorservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: interceptorservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: interceptorservice-editor-role
rules:
- apiGroups:
  - dp.wso2.com
  resources:
  - interceptorservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dp.wso2.com
  resources:
  - interceptorservices/status
  verbs:
  - get
