# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.idp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubernetes-gateway-helm.resource.prefix" . }}-idpui-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.idp.idpui.deployment.replicas }}
  strategy:
    type: {{ .Values.idp.idpui.deployment.strategy }}
  selector:
    matchLabels:
{{ include "kubernetes-gateway-helm.pod.selectorLabels" (dict "root" . "app" "idp-ui" ) | indent 6}}
  template:
    metadata:
      labels:
{{ include "kubernetes-gateway-helm.pod.selectorLabels" (dict "root" . "app" "idp-ui" ) | indent 8}}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: idpui
          image: {{ .Values.idp.idpui.deployment.image }}
          imagePullPolicy: {{ .Values.idp.idpui.deployment.imagePullPolicy }}
          ports:
            - containerPort: 9443
              protocol: "TCP"
          env:
          - name: IDP_LOGIN_URL
            value: {{ .Values.idp.idpui.configs.idpLoginUrl }}
          - name: IDP_AUTH_CALLBACK_URL
            value: {{ .Values.idp.idpui.configs.idpAuthCallBackUrl }}
          - name: SSL_CERT_PATH
            value: /home/wso2kgw/security/idp.crt
          - name: SSL_KEY_PATH
            value: /home/wso2kgw/security/idp.key
          readinessProbe:
            httpGet:
              path: /authenticationEndpoint/health
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.idp.idpui.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.idp.idpui.deployment.readinessProbe.periodSeconds }}    
          livenessProbe:
            httpGet:
              path: /authenticationEndpoint/health
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.idp.idpui.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.idp.idpui.deployment.livenessProbe.periodSeconds }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
{{ include "kubernetes-gateway-helm.deployment.resources" .Values.idp.idpui.deployment.resources | indent 10 }}
          volumeMounts:
            - name: idp-ui-tls-volume
              mountPath: /home/wso2kgw/security/idp.key
            {{- if and .Values.idp.idpui.configs .Values.idp.idpui.configs.tls }}
              subPath: {{ .Values.idp.idpui.configs.tls.certKeyFilename | default "tls.key" }}
            {{- else }}
              subPath: tls.key
            {{- end }}
            - name: idp-ui-tls-volume
              mountPath: /home/wso2kgw/security/idp.crt
            {{- if and .Values.idp.idpui.configs .Values.idp.idpui.configs.tls }}
              subPath: {{ .Values.idp.idpui.configs.tls.certFilename | default "tls.crt" }}
            {{- else }}
              subPath: tls.crt
            {{- end }}
      {{- if and .Values.wso2.subscription .Values.wso2.subscription.imagePullSecrets}}
      imagePullSecrets:
        - name: {{ .Values.wso2.subscription.imagePullSecrets }}
      {{ end }}      
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"

      volumes:
        - name: idp-ui-tls-volume
          secret:
       {{ if and .Values.idp.idpui.configs .Values.idp.idpui.configs.tls }}
            secretName: {{ .Values.idp.idpui.configs.tls.secretName | default (printf "%s-idp-ui-server-cert" (include "kubernetes-gateway-helm.resource.prefix" .)) }}
       {{ else }}
            secretName: {{ template "kubernetes-gateway-helm.resource.prefix" . }}-idp-ui-server-cert
       {{ end }}            
{{- end -}}
