openapi: 3.0.0
info:
  description: "Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)\
    \ or HTML."
  title: Sample API
  version: 0.1.9
servers:
- description: "Optional server description, e.g. Main (production) server"
  url: http://api.example.com/v1
- description: "Optional server description, e.g. Internal staging server for testing"
  url: http://staging-api.example.com
paths:
  /users:
    get:
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: A JSON array of user names
      summary: Returns a list of users.
      x-accepts: application/json
components:
  schemas: {}

