# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.wso2.apk.dp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-configmap
  namespace: {{ .Release.Namespace }}
data:
  Config.toml: |
    [ballerina.log]
    level = "DEBUG"
    [ballerina.http]
    traceLogConsole = true
    [wso2.runtime_domain_service.runtimeConfiguration.idpConfiguration]
    organizationClaim = "{{ .Values.wso2.apk.idp.organizationClaim }}"
    [wso2.runtime_domain_service.runtimeConfiguration.idpConfiguration.publicKey]
    certFilePath = "/home/wso2apk/runtime/security/mg.pem"
    [wso2.runtime_domain_service.runtimeConfiguration.keyStores.tls]
    keyFilePath = "/home/wso2apk/runtime/security/runtime.key"
    certFilePath = "/home/wso2apk/runtime/security/runtime.pem"
    [wso2.runtime_domain_service.runtimeConfiguration.keyStores.signing]
    keyFilePath = "/home/wso2apk/runtime/security/wso2carbon.key"
    [wso2.runtime_domain_service.runtimeConfiguration.gatewayConfiguration]
    name = "{{ .Values.wso2.apk.dp.gateway.name }}"
    listenerName = "{{ .Values.wso2.apk.dp.gateway.listener.name}}"
    {{  if .Values.wso2.apk.dp.controlPlane }}
    [wso2.runtime_domain_service.runtimeConfiguration.controlPlane]
    serviceBaseURl = "{{ .Values.wso2.apk.dp.controlPlane.serviceUrl | default (printf "http://%s-admin-ds-service:9444" (include "apk-helm.resource.prefix" .)) }}"
    enableAuthentication = {{ .Values.wso2.apk.dp.controlPlane.enableAuthentication | default true}}
    enableHostNameVerification = {{ .Values.wso2.apk.dp.controlPlane.enableHostNameVerification | default true}}
    [wso2.runtime_domain_service.runtimeConfiguration.controlPlane.certificate]
    certFilePath = "/home/wso2apk/runtime/security/controlplane.pem"
    {{  if .Values.wso2.apk.dp.controlPlane.headers }}
    {{- range $name, $val := $.Values.wso2.apk.dp.controlPlane.headers }}
    [[wso2.runtime_domain_service.runtimeConfiguration.controlPlane.headers]]
     name = "{{ $val.name }}"
     value = "{{ $val.value }}"
    {{- end }}
    {{- end }}
    {{ else }}
    [wso2.runtime_domain_service.runtimeConfiguration.controlPlane]
    serviceBaseURl = "https://{{ template "apk-helm.resource.prefix" . }}-admin-ds-service:9444/api/am/internal/v1"
    enableHostNameVerification = false
    [wso2.runtime_domain_service.runtimeConfiguration.controlPlane.certificate]
    certFilePath = "/home/wso2apk/runtime/security/controlplane.pem"
    {{- end }}   

{{- end -}}
