# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/dp.wso2.com_apis.yaml
- bases/cp.wso2.com_applications.yaml
- bases/dp.wso2.com_authentications.yaml
- bases/dp.wso2.com_apipolicies.yaml
- bases/cp.wso2.com_subscriptions.yaml
- bases/dp.wso2.com_scopes.yaml
- bases/dp.wso2.com_ratelimitpolicies.yaml
- bases/dp.wso2.com_airatelimitpolicies.yaml
- bases/dp.wso2.com_backends.yaml
- bases/dp.wso2.com_interceptorservices.yaml
- bases/dp.wso2.com_jwtissuers.yaml
- bases/dp.wso2.com_backendjwts.yaml
- bases/dp.wso2.com_tokenissuers.yaml
- bases/dp.wso2.com_gqlroutes.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_apis.yaml
#- patches/webhook_in_applications.yaml
#- patches/webhook_in_authentications.yaml
#- patches/webhook_in_apipolicies.yaml
#- patches/webhook_in_subscriptions.yaml
#- patches/webhook_in_scopes.yaml
#- patches/webhook_in_ratelimitpolicies.yaml
#- patches/webhook_in_backends.yaml
#- patches/webhook_in_interceptorservices.yaml
#- patches/webhook_in_jwtissuers.yaml
#- patches/webhook_in_backendjwts.yaml
#- patches/webhook_in_gqlroutes.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_apis.yaml
#- patches/cainjection_in_applications.yaml
#- patches/cainjection_in_authentications.yaml
#- patches/cainjection_in_apipolicies.yaml
#- patches/cainjection_in_subscriptions.yaml
#- patches/cainjection_in_scopes.yaml
#- patches/cainjection_in_ratelimitpolicies.yaml
#- patches/cainjection_in_backends.yaml
#- patches/cainjection_in_interceptorservices.yaml
#- patches/cainjection_in_jwtissuers.yaml
#- patches/cainjection_in_backendjwts.yaml
#- patches/cainjection_in_tokenissuers.yaml
#- patches/cainjection_in_gqlroutes.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
